In [1]:
import numpy as np
import tensorflow as tf

In [3]:
data = np.array(range(20))

In [6]:
def getBatch(data):
    epochs = 2
    loop = 0
    while loop < epochs:
        loop+=1
        print("epoch: ", loop)
        startIdx = -1
        while startIdx<len(data)-5:
            startIdx+=1
            print(startIdx)
            yield data[startIdx:startIdx+5]

In [7]:
for batch in getBatch(data):
    print(batch)

epoch:  1
0
[0 1 2 3 4]
1
[1 2 3 4 5]
2
[2 3 4 5 6]
3
[3 4 5 6 7]
4
[4 5 6 7 8]
5
[5 6 7 8 9]
6
[ 6  7  8  9 10]
7
[ 7  8  9 10 11]
8
[ 8  9 10 11 12]
9
[ 9 10 11 12 13]
10
[10 11 12 13 14]
11
[11 12 13 14 15]
12
[12 13 14 15 16]
13
[13 14 15 16 17]
14
[14 15 16 17 18]
15
[15 16 17 18 19]
epoch:  2
0
[0 1 2 3 4]
1
[1 2 3 4 5]
2
[2 3 4 5 6]
3
[3 4 5 6 7]
4
[4 5 6 7 8]
5
[5 6 7 8 9]
6
[ 6  7  8  9 10]
7
[ 7  8  9 10 11]
8
[ 8  9 10 11 12]
9
[ 9 10 11 12 13]
10
[10 11 12 13 14]
11
[11 12 13 14 15]
12
[12 13 14 15 16]
13
[13 14 15 16 17]
14
[14 15 16 17 18]
15
[15 16 17 18 19]
